spring:
  application:
    name: praesto

  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: Praesto

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${AUTH0_DOMAIN}/